import { 
  Heart, 
  MessageSquare, 
  Star, 
  Flower, 
  Calendar, 
  Compass, 
  Smile, 
  Users, 
  Camera, 
  Music, 
  PartyPopper, 
  Home, 
  Gift, 
  Utensils, 
  Image, 
  Flag, 
  GraduationCap, 
  Trophy, 
  Briefcase, 
  Cloud, 
  Settings,
  Trash2,
  Edit3,
  Plus,
  Search,
  LogOut,
  Menu,
  X,
  ChevronRight,
  LayoutDashboard,
  Map,
  FileText,
  Lock,
  Unlock,
  Check,
  ChevronLeft,
  Upload,
  HeartHandshake,
  ListChecks,
  Maximize2,
  MapPin,
  Bell,
  HelpCircle,
  SlidersHorizontal,
  ChevronDown,
  Eye,
  EyeOff
} from 'lucide-react';

const iconMap = {
  // Love Story
  heart: Heart,
  hearts: Heart,
  chat: MessageSquare,
  rings: HeartHandshake,
  flowers: Flower,
  date: Calendar,
  trip: Compass,
  
  // Friendship
  smiley: Smile,
  group: Users,
  camera: Camera,
  music: Music,
  party: PartyPopper,
  school: GraduationCap,
  
  // Family
  home: Home,
  festival: PartyPopper,
  gift: Gift,
  food: Utensils,
  album: Image,
  
  // Personal / Career
  flag: Flag,
  trophy: Trophy,
  career: Briefcase,
  dream: Cloud,
  
  // General UI
  star: Star,
  settings: Settings,
  trash: Trash2,
  edit: Edit3,
  plus: Plus,
  search: Search,
  logout: LogOut,
  menu: Menu,
  close: X,
  right: ChevronRight,
  left: ChevronLeft,
  dashboard: LayoutDashboard,
  map: Map,
  location: MapPin,
  notes: FileText,
  lock: Lock,
  unlock: Unlock,
  check: Check,
  upload: Upload,
  manage: ListChecks,
  zoom: Maximize2,
  bell: Bell,
  help: HelpCircle,
  sliders: SlidersHorizontal,
  down: ChevronDown,
  eye: Eye,
  eyeoff: EyeOff
};

export const getIcon = (name, props = {}) => {
  const IconComponent = iconMap[name?.toLowerCase()] || Star;
  return <IconComponent {...props} />;
};
